### ISSUE TITLE
High resolution video cause cuda out of memory

### ISSUE THREAD

**Issue by 1059692261** [Sxjdwang/TalkLip#2]
Dear authors, thank you for your wonderful project!
When trying to run inf_demo.py on a 10s(30fps) video with a resolution of 1920 * 1080, I encountered a cuda out of memory error.  I was running the script on a NVIDIA RTX A6000 with 48GB memory,  and I thought it was enough to do the inference on a short 1080p video. Could you tell me what am I missing?

**Comment by Sxjdwang** [comment]
Inf_demo.py contain a face detection network to preprocess videos. I think that network causes memory insufficiency.

**Comment by 1059692261** [comment]
Thank you for your reply! However, I did the same inference using wav2lip and it worked out fine. I notice wav2lip uses the same face detection network as yours.

**Comment by Sxjdwang** [comment]
Can you show the line where "out of memory" occurs or more details of the error?

**Comment by phoenix8875** [comment]
Traceback (most recent call last):
  File "/content/TalkLip/inf_demo.py", line 280, in <module>
    synt_demo(fa, device, model, args)
  File "/content/TalkLip/inf_demo.py", line 225, in synt_demo
    inps, spectrogram, idAudio, padding_mask, imgs, bbxs = data_preprocess(args, face_detector)
  File "/content/TalkLip/inf_demo.py", line 190, in data_preprocess
    bbxs = detect_bbx(imgs, face_detector)
  File "/content/TalkLip/inf_demo.py", line 106, in detect_bbx
    preds = fa.get_detections_for_batch(np.asarray(fb))
  File "/content/TalkLip/face_detection/api.py", line 66, in get_detections_for_batch
    detected_faces = self.face_detector.detect_from_batch(images.copy())
  File "/content/TalkLip/face_detection/detection/sfd/sfd_detector.py", line 42, in detect_from_batch
    bboxlists = batch_detect(self.face_detector, images, device=self.device)
  File "/content/TalkLip/face_detection/detection/sfd/detect.py", line 80, in batch_detect
    olist1 = net(imgs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/TalkLip/face_detection/detection/sfd/net_s3fd.py", line 71, in forward
    h = F.relu(self.conv1_1(x))
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/functional.py", line 1457, in relu
    result = torch.relu(input)
RuntimeError: CUDA out of memory. Tried to allocate 7.03 GiB (GPU 0; 14.75 GiB total capacity; 7.96 GiB already allocated; 5.68 GiB free; 8.01 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Sxjdwang** [comment]
It is caused by a face detection network for preprocessing. You may feed a high-resolution video to it. In order to solve this problem, you can reduce batch size for the face detection network by changing "32" in the 102-th line of inf_demo.py to a lower number. "batches = [frames[i:i + 32] for i in range(0, len(frames), 32)]"
